apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-yjee
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-yjee
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-yjee
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-yjee
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-yjee
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vuhe-tenant/rhtap-demo-app/hacbs-test-project-yjee@sha256:be8daccc6ffed2d73d091ac2c933343131959c1a66af8c3b324da8168f5800b9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
